### ISSUE TITLE
Make the plugin compatible with latest Intellij IDEs 2022.2

### ISSUE THREAD

**Issue by akhilerm** [lunakoly/QuickLink#10]
I am using GoLand 2022.2.4, but this plugin is not supported. The supported versions are I guess are listed in https://github.com/lunakoly/QuickLink/blob/main/gradle.properties#L10-L15. 

If adding `2022.2` to the properties can help with updating or releasing a new version, I can raise a PR for those changes. I am not sure of the additional testing that is involved with releasing a new version.

**Comment by lunakoly** [comment]
Hi! Thanks for your interest, I'll update the value

**Comment by akhilerm** [comment]
Thank you @lunakoly !!!. Can you also release a new version so that it can be used from `plugins.jebrains.com`

**Comment by lunakoly** [comment]
Done :) [Available here](https://github.com/lunakoly/QuickLink/releases/tag/v1.0.3). We'll have to wait until it reaches the marketplace, though.

**Comment by akhilerm** [comment]
@lunakoly Can you update for the latest 231.* version of the intellij IDEs and release a new version. The plugin is now incompatible with latest Goland.

I am not sure which versions of IDEs we should support. If we have an idea about that, I can raise the PR to add new version to the support matrix.
